name: Build and Publish website

on:
  push:
    branches: [ "main", "actions" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Produce Browser Distribution
        run: ./gradlew wasmJsBrowserDistribution

      - name: "Clone release"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: release
          path: release

      - run: ls composeApp/build/dist/wasmJs/productionExecutable

      - name: Prepare repository
        run: |
          mv composeApp/build/dist/wasmJs/productionExecutable/* ./release

      - name: Publish
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "release"
          add: "."
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Automatic commit, run id: ${{ github.run_id }}"
          push: true
      
  # dependency-submission:

  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #       java-version: '21'
  #       distribution: 'temurin'

  #   - name: Generate and submit dependency graph
  #     uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
