name: Build and Publish website

on:
  push:
    branches: [ "main", "actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Produce Browser Distribution
      run: ./gradlew wasmJsBrowserDistribution

    - name: "Clone release"
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        ref: release
        path: release


    - name: Publish
      run: |
        mv composeApp/build/dist/wasmJs/productionExecutable/* ./release
        cd release
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Automatic commit, run id: ${{ github.run_id }}"
        git push
      
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
